## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
# Google Colab attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df = pd.read_csv('./Resources/attrition.csv')
attrition_df.head()

,Unnamed: 0,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,...,3,1,0,8,0,1,6,4,0,5
1,1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,...,4,4,1,10,3,3,10,7,1,7
2,2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,...,3,2,0,7,3,3,0,0,0,0
3,3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,...,3,3,0,8,3,3,8,7,3,0
4,4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,...,3,4,1,6,3,3,2,2,2,2

In [2]:
# Look at numver of null values
attrition_df.isnull().sum()

Unnamed: 0                  0
Age                         0
Attrition                   0
BusinessTravel              0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EnvironmentSatisfaction     0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [3]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Unnamed: 0                  1470
Age                           43
Attrition                      2
BusinessTravel                 3
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EnvironmentSatisfaction        4
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
NumCompaniesWorked            10
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

y_df.head()

  Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [5]:
# Create a list of at least 10 column names to use as X data
selected_columns = ['Age', 'BusinessTravel', 'DistanceFromHome', 'Education', 'EducationField', 'EnvironmentSatisfaction', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']


# Create X_df using your selected columns
X_df = attrition_df[selected_columns]


# Show the data types for X_df
X_df.dtypes

Age                          int64
BusinessTravel              object
DistanceFromHome             int64
Education                    int64
EducationField              object
EnvironmentSatisfaction      int64
EnvironmentSatisfaction      int64
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [6]:
# Display X_df
X_df.head()

,Age,BusinessTravel,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Travel_Rarely,1,2,Life Sciences,2,2,94,3,2,...,3,1,0,8,0,1,6,4,0,5
1,49,Travel_Frequently,8,1,Life Sciences,3,3,61,2,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Travel_Rarely,2,2,Other,4,4,92,2,1,...,3,2,0,7,3,3,0,0,0,0
3,33,Travel_Frequently,3,4,Life Sciences,4,4,56,3,1,...,3,3,0,8,3,3,8,7,3,0
4,27,Travel_Rarely,2,1,Medical,1,1,40,3,1,...,3,4,1,6,3,3,2,2,2,2

In [7]:
#Preprocess Y data Binary Field with label encoding

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
y_df['Attrition'] = le.fit_transform(y_df['Attrition'])

# Use OneHotEncoder for multi-categorical field
dept_encoder = OneHotEncoder(sparse_output=False)
dept_encoded =dept_encoder.fit_transform(y_df[['Department']])
dept_encoded_columns = dept_encoder.get_feature_names_out(['Department'])
dept_encoded_df = pd.DataFrame(dept_encoded, columns=dept_encoded_columns)

y_df_processed = pd.concat([y_df, dept_encoded_df], axis=1)

# Drop Attrition and Department columns
y_df_processed = y_df_processed.drop(columns=['Department'])

y_df_processed.rename(columns={'Department_Human Resources':'Department_Human_Resources', 'Department_Research & Development':'Department_Research_and_Development'}, inplace=True)
y_df_processed.head(20)

C:\Users\dgerhart\AppData\Local\Temp\ipykernel_52508\1952217704.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_df['Attrition'] = le.fit_transform(y_df['Attrition'])

,Attrition,Department_Human_Resources,Department_Research_and_Development,Department_Sales
0,1,0.0,0.0,1.0
1,0,0.0,1.0,0.0
2,1,0.0,1.0,0.0
3,0,0.0,1.0,0.0
4,0,0.0,1.0,0.0
5,0,0.0,1.0,0.0
6,0,0.0,1.0,0.0
7,0,0.0,1.0,0.0
8,0,0.0,1.0,0.0
9,0,0.0,1.0,0.0
10,0,0.0,1.0,0.0
11,0,0.0,1.0,0.0
12,0,0.0,1.0,0.0
13,0,0.0,1.0,0.0
14,1,0.0,1.0,0.0
15,0,0.0,1.0,0.0
16,0,0.0,1.0,0.0
17,0,0.0,1.0,0.0
18,0,0.0,0.0,1.0
19,0,0.0,1.0,0.0

In [8]:
# Preprocess X data 

#Use Label Encoder for binary field Overtime
X_df['OverTime'] = le.fit_transform(X_df['OverTime'])

# Use OneHotEncoder for multi-categorical fields

# Encode BusinessTravel
biz_travel_encoder = OneHotEncoder(sparse_output=False)
biz_travel_encoded = biz_travel_encoder.fit_transform(X_df[['BusinessTravel']])
biz_travel_encoded_columns = biz_travel_encoder.get_feature_names_out(['BusinessTravel'])
biz_travel_encoded_df = pd.DataFrame(biz_travel_encoded, columns=biz_travel_encoded_columns)

# Encode EducationField
edu_field_encoder = OneHotEncoder(sparse_output=False)
edu_field_encoded =edu_field_encoder.fit_transform(X_df[['EducationField']])
edu_field_encoded_columns = edu_field_encoder.get_feature_names_out(['EducationField'])
edu_field_encoded_df = pd.DataFrame(edu_field_encoded, columns=edu_field_encoded_columns)

# Encode JobRole
job_role_encoder = OneHotEncoder(sparse_output=False)
job_role_encoded =job_role_encoder.fit_transform(X_df[['JobRole']])
job_role_encoded_columns = job_role_encoder.get_feature_names_out(['JobRole'])
job_role_encoded_df = pd.DataFrame(job_role_encoded, columns=job_role_encoded_columns)

# Encode MaritalStatus
marital_status_encoder = OneHotEncoder(sparse_output=False)
marital_status_encoded =marital_status_encoder.fit_transform(X_df[['MaritalStatus']])
marital_status_encoded_columns = marital_status_encoder.get_feature_names_out(['MaritalStatus'])
marital_status_encoded_df = pd.DataFrame(marital_status_encoded, columns=marital_status_encoded_columns)

# Concatenate the X dataframes
X_processed_df = pd.concat([X_df, biz_travel_encoded_df, edu_field_encoded_df, job_role_encoded_df, marital_status_encoded_df], axis=1)

# Drop original columns
X_processed_df = X_processed_df.drop(columns=['BusinessTravel', 'EducationField', 'JobRole', 'MaritalStatus'])

pd.set_option('display.max_columns', None)
X_processed_df.head()

C:\Users\dgerhart\AppData\Local\Temp\ipykernel_52508\2979165779.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_df['OverTime'] = le.fit_transform(X_df['OverTime'])

,Age,DistanceFromHome,Education,EnvironmentSatisfaction,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,41,1,2,2,2,94,3,2,4,8,1,11,3,1,0,8,0,1,6,4,0,5,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,49,8,1,3,3,61,2,2,2,1,0,23,4,4,1,10,3,3,10,7,1,7,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,37,2,2,4,4,92,2,1,3,6,1,15,3,2,0,7,3,3,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,33,3,4,4,4,56,3,1,3,1,1,11,3,3,0,8,3,3,8,7,3,0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,27,2,1,1,1,40,3,1,2,9,0,12,3,4,1,6,3,3,2,2,2,2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [24]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

y_processed_attrition_df = y_df_processed['Attrition']

y_processed_department_df = y_df_processed[['Department_Human_Resources', 'Department_Research_and_Development', 'Department_Sales']]

X_train, X_test, y_attrition_train, y_attrition_test, y_department_train, y_department_test = train_test_split(X_processed_df, y_processed_attrition_df, y_processed_department_df)

X_train.head()

,Age,DistanceFromHome,Education,EnvironmentSatisfaction,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
941,30,6,3,1,1,48,2,2,4,0,0,12,3,1,1,10,6,3,9,2,6,7,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1175,39,12,3,4,4,66,3,2,2,4,0,21,4,3,0,7,3,3,5,4,1,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1172,29,10,3,3,3,42,2,2,3,9,0,11,3,3,0,8,2,3,5,2,1,4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1463,31,5,3,2,2,74,3,2,1,0,0,19,3,2,0,10,2,3,9,4,1,7,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1308,38,2,4,2,2,77,1,2,4,2,1,20,4,1,2,20,4,2,4,2,0,3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [10]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

# ***** Already preprocessed all data to numeric data types *****

In [25]:
# Create a StandardScaler
scaler = StandardScaler()


# Fit the StandardScaler to the training data
X_scaler = scaler.fit(X_train)


# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
# Create a OneHotEncoder for the Department column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data

# ***** Already preprocessed all data to numeric data types *****

In [13]:
# Create a OneHotEncoder for the Attrition column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data

# ***** Already preprocessed all data to numeric data types *****

## Create, Compile, and Train the Model

In [26]:
# Find the number of columns in the X training data
column_count = X_train_scaled.shape[1]

# Create the input layer
input = layers.Input(shape=(column_count,), name='InputLayer')

# Create at least two shared layers
shared1 = layers.Dense(64, activation='relu')(input)
shared2 = layers.Dense(128, activation='relu')(shared1)

In [27]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden = layers.Dense(32, activation='relu')(shared2)

# Create the output layer
department_output = layers.Dense(3, activation='softmax', name='department')(department_hidden)

In [28]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(32, activation='relu')(shared2)

# Create the output layer
attrition_output = layers.Dense(1, activation='sigmoid', name='attrition')(attrition_hidden)

In [29]:
# Create the model
model = Model(inputs=input, outputs=[department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'department': 'categorical_crossentropy', 'attrition': 'binary_crossentropy'},
              metrics={'department': 'accuracy', 'attrition': 'accuracy'})


# Summarize the model
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ InputLayer          │ (None, 43)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 64)        │      2,816 │ InputLayer[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 128)       │      8,320 │ dense_4[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 32)        │      4,128 │ dense_5[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 32)        │      4,128 │ dense_5[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department (Dense)  │ (None, 3)         │         99 │ dense_6[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition (Dense)   │ (None, 1)         │         33 │ dense_7[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 19,524 (76.27 KB)

 Trainable params: 19,524 (76.27 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
# Train the model
model.fit(X_train_scaled,
           {'department': y_department_train, 
            'attrition': y_attrition_train}, 
            epochs=100, 
            batch_size=32, 
            validation_split=.2,
            verbose=2)

Epoch 1/100
28/28 - 3s - 92ms/step - attrition_accuracy: 0.7582 - department_accuracy: 0.6186 - loss: 1.3453 - val_attrition_accuracy: 0.8462 - val_department_accuracy: 0.8281 - val_loss: 1.0489
Epoch 2/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.8388 - department_accuracy: 0.8910 - loss: 0.7995 - val_attrition_accuracy: 0.8462 - val_department_accuracy: 0.9276 - val_loss: 0.7177
Epoch 3/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.8422 - department_accuracy: 0.9535 - loss: 0.5288 - val_attrition_accuracy: 0.8597 - val_department_accuracy: 0.9412 - val_loss: 0.5550
Epoch 4/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.8695 - department_accuracy: 0.9773 - loss: 0.4182 - val_attrition_accuracy: 0.8733 - val_department_accuracy: 0.9548 - val_loss: 0.4972
Epoch 5/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.8831 - department_accuracy: 0.9841 - loss: 0.3565 - val_attrition_accuracy: 0.8733 - val_department_accuracy: 0.9548 - val_loss: 0.4878
Epoch 6/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.8944 - department_accuracy: 0.9921 - loss: 0.3170 - val_attrition_accuracy: 0.8869 - val_department_accuracy: 0.9683 - val_loss: 0.4483
Epoch 7/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.8967 - department_accuracy: 0.9852 - loss: 0.2986 - val_attrition_accuracy: 0.9005 - val_department_accuracy: 0.9638 - val_loss: 0.4503
Epoch 8/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9126 - department_accuracy: 0.9943 - loss: 0.2619 - val_attrition_accuracy: 0.8959 - val_department_accuracy: 0.9502 - val_loss: 0.4748
Epoch 9/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9274 - department_accuracy: 0.9955 - loss: 0.2360 - val_attrition_accuracy: 0.9095 - val_department_accuracy: 0.9548 - val_loss: 0.4683
Epoch 10/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9274 - department_accuracy: 0.9966 - loss: 0.2192 - val_attrition_accuracy: 0.8914 - val_department_accuracy: 0.9638 - val_loss: 0.4601
Epoch 11/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9398 - department_accuracy: 0.9977 - loss: 0.1957 - val_attrition_accuracy: 0.9005 - val_department_accuracy: 0.9502 - val_loss: 0.4926
Epoch 12/100
28/28 - 0s - 5ms/step - attrition_accuracy: 0.9444 - department_accuracy: 1.0000 - loss: 0.1791 - val_attrition_accuracy: 0.9050 - val_department_accuracy: 0.9548 - val_loss: 0.4985
Epoch 13/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9410 - department_accuracy: 1.0000 - loss: 0.1696 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9593 - val_loss: 0.4980
Epoch 14/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9501 - department_accuracy: 1.0000 - loss: 0.1470 - val_attrition_accuracy: 0.8914 - val_department_accuracy: 0.9502 - val_loss: 0.5219
Epoch 15/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9501 - department_accuracy: 1.0000 - loss: 0.1353 - val_attrition_accuracy: 0.8914 - val_department_accuracy: 0.9593 - val_loss: 0.5332
Epoch 16/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9682 - department_accuracy: 1.0000 - loss: 0.1173 - val_attrition_accuracy: 0.8959 - val_department_accuracy: 0.9548 - val_loss: 0.5439
Epoch 17/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9762 - department_accuracy: 1.0000 - loss: 0.0933 - val_attrition_accuracy: 0.8869 - val_department_accuracy: 0.9548 - val_loss: 0.5567
Epoch 18/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9818 - department_accuracy: 1.0000 - loss: 0.0810 - val_attrition_accuracy: 0.8959 - val_department_accuracy: 0.9593 - val_loss: 0.5793
Epoch 19/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9852 - department_accuracy: 1.0000 - loss: 0.0732 - val_attrition_accuracy: 0.8869 - val_department_accuracy: 0.9548 - val_loss: 0.6019
Epoch 20/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9886 - department_accuracy: 1.0000 - loss: 0.0570 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.6152
Epoch 21/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9898 - department_accuracy: 1.0000 - loss: 0.0475 - val_attrition_accuracy: 0.8959 - val_department_accuracy: 0.9548 - val_loss: 0.6563
Epoch 22/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9943 - department_accuracy: 1.0000 - loss: 0.0381 - val_attrition_accuracy: 0.8869 - val_department_accuracy: 0.9548 - val_loss: 0.6746
Epoch 23/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9943 - department_accuracy: 1.0000 - loss: 0.0296 - val_attrition_accuracy: 0.8914 - val_department_accuracy: 0.9548 - val_loss: 0.6796
Epoch 24/100
28/28 - 0s - 4ms/step - attrition_accuracy: 0.9977 - department_accuracy: 1.0000 - loss: 0.0236 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.7006
Epoch 25/100
28/28 - 0s - 5ms/step - attrition_accuracy: 0.9989 - department_accuracy: 1.0000 - loss: 0.0185 - val_attrition_accuracy: 0.8733 - val_department_accuracy: 0.9548 - val_loss: 0.7173
Epoch 26/100
28/28 - 0s - 5ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0152 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 0.7530
Epoch 27/100
28/28 - 0s - 5ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0121 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 0.7680
Epoch 28/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0104 - val_attrition_accuracy: 0.8869 - val_department_accuracy: 0.9548 - val_loss: 0.7891
Epoch 29/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0088 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.8029
Epoch 30/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0069 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.8327
Epoch 31/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0062 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.8324
Epoch 32/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0058 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.8489
Epoch 33/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0047 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.8620
Epoch 34/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0041 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 0.8874
Epoch 35/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0037 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.8937
Epoch 36/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0034 - val_attrition_accuracy: 0.8733 - val_department_accuracy: 0.9548 - val_loss: 0.9095
Epoch 37/100
28/28 - 0s - 5ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0030 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.9246
Epoch 38/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0027 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 0.9360
Epoch 39/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0024 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.9438
Epoch 40/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0023 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.9550
Epoch 41/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0020 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.9665
Epoch 42/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0019 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.9722
Epoch 43/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0017 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.9905
Epoch 44/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0016 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 0.9913
Epoch 45/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0015 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0044
Epoch 46/100
28/28 - 0s - 5ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0014 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0172
Epoch 47/100
28/28 - 0s - 5ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0013 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0176
Epoch 48/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0012 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0331
Epoch 49/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0011 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0373
Epoch 50/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 0.0010 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0476
Epoch 51/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 9.7804e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0525
Epoch 52/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 9.2313e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0595
Epoch 53/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 8.7606e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0670
Epoch 54/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 8.1303e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.0758
Epoch 55/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 7.6333e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0794
Epoch 56/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 7.2078e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0876
Epoch 57/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 6.8557e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0927
Epoch 58/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 6.4892e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.0997
Epoch 59/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 6.1044e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1082
Epoch 60/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 5.7352e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1146
Epoch 61/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 5.4767e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1219
Epoch 62/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 5.2017e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1243
Epoch 63/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 4.9351e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1320
Epoch 64/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 4.7085e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1366
Epoch 65/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 4.5389e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1423
Epoch 66/100
28/28 - 0s - 5ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 4.2696e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.1478
Epoch 67/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 4.0751e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.1529
Epoch 68/100
28/28 - 0s - 5ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 3.9144e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.1614
Epoch 69/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 3.7407e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1646
Epoch 70/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 3.5638e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.1692
Epoch 71/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 3.3986e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1731
Epoch 72/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 3.2558e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1803
Epoch 73/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 3.1227e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1840
Epoch 74/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.9839e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1909
Epoch 75/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.8816e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.1938
Epoch 76/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.7473e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.1986
Epoch 77/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.6310e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2018
Epoch 78/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.5239e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2084
Epoch 79/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.4303e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2116
Epoch 80/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.3181e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2180
Epoch 81/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.2338e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.2220
Epoch 82/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.1503e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2251
Epoch 83/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 2.0761e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2282
Epoch 84/100
28/28 - 0s - 6ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.9997e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2351
Epoch 85/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.9239e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2370
Epoch 86/100
28/28 - 0s - 5ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.8515e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.2402
Epoch 87/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.7866e-04 - val_attrition_accuracy: 0.8824 - val_department_accuracy: 0.9548 - val_loss: 1.2452
Epoch 88/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.7251e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2483
Epoch 89/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.6677e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2546
Epoch 90/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.6022e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2562
Epoch 91/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.5553e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2605
Epoch 92/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.4999e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2628
Epoch 93/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.4460e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2687
Epoch 94/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.3923e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2701
Epoch 95/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.3509e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2765
Epoch 96/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.3008e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2778
Epoch 97/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.2616e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2808
Epoch 98/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.2169e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2857
Epoch 99/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.1803e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2892
Epoch 100/100
28/28 - 0s - 4ms/step - attrition_accuracy: 1.0000 - department_accuracy: 1.0000 - loss: 1.1502e-04 - val_attrition_accuracy: 0.8778 - val_department_accuracy: 0.9548 - val_loss: 1.2919

In [31]:
# Evaluate the model with the testing data
results = model.evaluate(X_test_scaled,
                                            {'department': y_department_test, 
                                             'attrition': y_attrition_test},
                                             verbose=2)

12/12 - 0s - 4ms/step - attrition_accuracy: 0.8234 - department_accuracy: 0.9701 - loss: 1.8691

In [35]:
# Print the accuracy for both department and attrition

print(f"Attrition Accuracy: {results[1]*100:.2f}% Department Accuracy: {results[2]*100:.2f}% Loss: {results[0]:.4f}")
results

Attrition Accuracy: 82.34% Department Accuracy: 97.01% Loss: 1.8691

[1.8690659999847412, 0.823369562625885, 0.970108687877655]

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Yes, I believe Accuracy is the best metric because the cost of being wrong is high.  For example, if could be extremely costly if a key employee is predicted not to leave but they do.  If you believe they will leave and they don't that's less problematic because there won't be much harm in trying to address the factors that indicate that they will leave.  (FAR less expesive to retain than to replace and train.)  It's important to know the key contribution factors to attrition though so further analysis would be needed to determine this.  Once known those key features can be used to build a retention plan for those that look like they will leave the company.
2. For Department I chose softmax.  Softmax will always choose one and this would create a false positive if an unseen value were to show up in the 'department' data. Softmax is a good choice when the result is non binary but all the data will match one of the values seen in the data.  For Attrition I chose sigmoid as it's ideal for binary data.
3. It would be ideal to have employment and salary history or the employees past positions.  Since this information is often aquired during the interview process it should be available.  This would allow the model to recognize job change patterns and use that to improve accuracy.